## Model used: https://github.com/aws-neuron/aws-neuron-eks-samples/tree/master/mlp_train
apiVersion: v1
kind: DaemonSet
metadata:
  name: neuron-sample
  labels:
    app: neuron-sample
spec:
  restartPolicy: Never
  schedulerName: default-scheduler
  nodeSelector:
    beta.kubernetes.io/instance-type: trn1.2xlarge
  containers:
    - name: neuron-sample
      command: [ 'torchrun' ]
      args:
        - '--nnodes=1'
        - '--nproc_per_node=2'
        - 'train_torchrun.py'
      image: 654654461386.dkr.ecr.us-west-2.amazonaws.com/mlp-neuron-sample:mlp
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          aws.amazon.com/neuroncore: 2


